# read_tdl_file: a function for reading the data from a `.dat` file generated by
# the Bernacchi lab's tunable diode laser (TDL) system into an exdf object.
#
# ------------------------------------------------------------------------------
#
# INPUTS:
#
# - file_name: a relative or absolute path to a `.dat` file containing TDL
#       data
#
# - rows_to_skip: the number of rows to skip at the beginning of the file; the
#       first row in one of these TDL files typically has fewer columns than the
#       others, which causes problems when storing it as an R data frame
#
# - variable_name_row: the row number in the TDL file containing the names of
#       the variables, e.g. "RECORD", "Conc12C_Avg", etc
#
# - variable_unit_row: the row number in the TDL file containing the units of
#       the variables, e.g. "ppm", "V", etc
#
# - data_start_row: the first row number of the table containing the measured
#       data in the TDL file
#
# - timestamp_colname: the name of the column that contains the timestamp of
#       each measurement
#
# ------------------------------------------------------------------------------
#
# OUTPUT:
#
# an exdf object with the following "extra" elements that fully includes all the
# data from the TDL file:
#
# - file_name: a copy of the input argument with the same name
#
# - rows_to_skip: a copy of the input argument with the same name
#
# - variable_name_row: a copy of the input argument with the same name
#
# - variable_unit_row: a copy of the input argument with the same name
#
# - data_start_row: a copy of the input argument with the same name
#
# - timestamp_colname: a copy of the input argument with the same name
#
read_tdl_file <- function(
    file_name,
    rows_to_skip,
    variable_name_row,
    variable_unit_row,
    data_start_row,
    timestamp_colname
)
{
    raw_tdl <- utils::read.csv(
        file_name,
        header = FALSE,
        skip = rows_to_skip
    )

    tdl_variable_names <- raw_tdl[variable_name_row - rows_to_skip,]
    tdl_variable_units <- raw_tdl[variable_unit_row - rows_to_skip,]
    tdl_data <- raw_tdl[seq(data_start_row - rows_to_skip, nrow(raw_tdl)),]

    # Convert the data to numeric values whenever possible
    tdl_data <- as.data.frame(
        lapply(tdl_data, try_as_numeric),
        stringsAsFactors = FALSE
    )

    # Set the column names
    colnames(tdl_data) <- tdl_variable_names
    colnames(tdl_variable_units) <- tdl_variable_names

    # Remove the row names that appeared after subsetting
    row.names(tdl_data) <- NULL
    row.names(tdl_variable_units) <- NULL

    # Make sure the timestamp column is properly interpreted
    tdl_data[[timestamp_colname]] <-
        as.POSIXlt(tdl_data[[timestamp_colname]], origin = "1970-01-01")

    # Make a "categories" data frame
    tdl_variable_categories <- tdl_variable_units
    tdl_variable_categories[1,] <- "Raw TDL"

    return(
        exdf(
            tdl_data,
            tdl_variable_units,
            tdl_variable_categories,
            file_name = file_name,
            rows_to_skip = rows_to_skip,
            variable_name_row = variable_name_row,
            variable_unit_row = variable_unit_row,
            data_start_row = data_start_row,
            timestamp_colname = timestamp_colname
        )
    )
}

# batch_read_tdl_file: a function for reading the data from multiple Licor
# Excel files into an R list.
#
# ------------------------------------------------------------------------------
#
# INPUTS:
#
# - file_names: a vector of relative or absolute paths to files containing TDL
#       data
#
# All other inputs are identical to those in the `read_tdl_file` function.
#
# ------------------------------------------------------------------------------
#
# OUTPUT:
#
# a list with unnamed elements, each of which is an exdf object representing the
# contents of a TDL file
#
batch_read_tdl_file <- function(
    file_names,
    rows_to_skip,
    variable_name_row,
    variable_unit_row,
    data_start_row,
    timestamp_colname = 'TIMESTAMP'
)
{
    lapply(
        file_names,
        function(filename) {
            read_tdl_file(
                    filename,
                    rows_to_skip,
                    variable_name_row,
                    variable_unit_row,
                    data_start_row,
                    timestamp_colname
            )
        }
    )
}

# choose_input_tdl_files: a function for interactively selecting multiple TDL
# data files.
#
# Important note: this function is only available on MS Windows.
#
# ------------------------------------------------------------------------------
#
# INPUTS:
#
# None
#
# ------------------------------------------------------------------------------
#
# OUTPUT:
#
# a vector of file name strings representing absolute paths to TDL files
#
choose_input_tdl_files <- function()
{
    if (!interactive() | .Platform$OS.type != "windows") {
        stop(
            paste(
                "The `choose_input_tdl_files` function is only available in",
                "interactive R sessions running in MS Windows"
            )
        )
    }

    utils::choose.files(
        default = "",
        caption = "Select TDL input files",
        multi = TRUE,
        filters = matrix(
            c(
                "TDL files (*.dat)", "All files (*.*)",
                "*.dat", "*.*"
            ),
            ncol = 2
        ),
        index = 1
    )
}
