# read_tdl_file: a function for reading the data from a `.dat` file generated by
# the Bernacchi lab's tunable diode laser (TDL) system into an R list.
#
# ------------------------------------------------------------------------------
#
# INPUTS:
#
# - file_name: a relative or absolute path to a `.dat` file containing TDL
#       data
#
# - rows_to_skip: the number of rows to skip at the beginning of the file; the
#       first row in one of these TDL files typically has fewer columns than the
#       others, which causes problems when storing it as an R data frame
#
# - variable_name_row: the row number in the TDL file containing the names of
#       the variables, e.g. "RECORD", "Conc12C_Avg", etc
#
# - variable_unit_row: the row number in the TDL file containing the units of
#       the variables, e.g. "ppm", "V", etc
#
# - data_start_row: the first row number of the table containing the measured
#       data in the TDL file
#
# - timestamp_colname: the name of the column that contains the timestamp of
#       each measurement
#
# ------------------------------------------------------------------------------
#
# OUTPUT:
#
# a list with the following named elements that together fully include all the
# data from the Licor Excel file:
#
# - file_name: a copy of the input argument with the same name
#
# - type: a data frame with one row and named columns, where the column names
#       are the variable names and the row indicates that all these values are
#       "raw", i.e., direct from the TDL without any analysis
#
# - units: a data frame with one row and named columns, where the column names
#       are the variable names and the row describes the units of each variable
#
# - main_data: a data frame with named columns, where the column names are the
#       variable names and the rows represent the measurements that were stored
#       in the original TDL file
#
# - rows_to_skip: a copy of the input argument with the same name
#
# - variable_name_row: a copy of the input argument with the same name
#
# - variable_unit_row: a copy of the input argument with the same name
#
# - data_start_row: a copy of the input argument with the same name
#
# - timestamp_colname: a copy of the input argument with the same name
#
read_tdl_file <- function(
    file_name,
    rows_to_skip,
    variable_name_row,
    variable_unit_row,
    data_start_row,
    timestamp_colname
)
{
    raw_tdl <- read.csv(
        file_name,
        header = FALSE,
        skip = rows_to_skip
    )

    tdl_variable_names <- raw_tdl[variable_name_row - rows_to_skip,]
    tdl_variable_units <- raw_tdl[variable_unit_row - rows_to_skip,]
    tdl_data <- raw_tdl[seq(data_start_row - rows_to_skip, nrow(raw_tdl)),]

    # Convert the data to numeric values whenever possible
    tdl_data <- as.data.frame(
        lapply(
            tdl_data,
            function(x) {
                # Try to apply as.numeric, but if any warnings or errors occur,
                # just use the original column values
                tryCatch(
                    {
                        # Code to be executed initially
                        as.numeric(x)
                    },
                    error=function(cond) {
                        # Code for handling errors
                        x
                    },
                    warning=function(cond) {
                        # Code for handling warnings
                        x
                    }
                )
            }
        ),
        stringsAsFactors = FALSE
    )

    # Set the column names
    colnames(tdl_data) <- tdl_variable_names
    colnames(tdl_variable_units) <- tdl_variable_names

    # Remove the row names that appeared after subsetting
    row.names(tdl_data) <- NULL
    row.names(tdl_variable_units) <- NULL

    # Make sure the timestamp column is properly interpreted
    tdl_data[[timestamp_colname]] <-
        as.POSIXlt(tdl_data[[timestamp_colname]], origin = "1970-01-01")

    # Make a "type" data frame
    tdl_type <- tdl_variable_units
    tdl_type[1,] <- "Raw TDL"

    return(
        list(
            file_name = file_name,
            type = tdl_type,
            units = tdl_variable_units,
            main_data = tdl_data,
            rows_to_skip = rows_to_skip,
            variable_name_row = variable_name_row,
            variable_unit_row = variable_unit_row,
            data_start_row = data_start_row,
            timestamp_colname = timestamp_colname
        )
    )
}

# batch_read_tdl_file: a function for reading the data from multiple Licor
# Excel files into an R list.
#
# ------------------------------------------------------------------------------
#
# INPUTS:
#
# - file_names: a vector of relative or absolute paths to files containing TDL
#       data
#
# All other inputs are identical to those in the `read_tdl_file` function.
#
# ------------------------------------------------------------------------------
#
# OUTPUT:
#
# a list with unnamed elements, each of which is a list describing the contents
# of a Licor file that was created using the the `read_tdl_file` function.
#
batch_read_tdl_file <- function(
    file_names,
    rows_to_skip = 1,
    variable_name_row = 2,
    variable_unit_row = 3,
    data_start_row = 5,
    timestamp_colname = 'TIMESTAMP'
)
{
    lapply(
        file_names,
        function(filename) {
            read_tdl_file(
                    filename,
                    rows_to_skip,
                    variable_name_row,
                    variable_unit_row,
                    data_start_row,
                    timestamp_colname
            )
        }
    )
}

# choose_input_tdl_files: a function for interactively selecting multiple TDL
# data files.
#
# Important note: this function is only available on MS Windows.
#
# ------------------------------------------------------------------------------
#
# INPUTS:
#
# None
#
# ------------------------------------------------------------------------------
#
# OUTPUT:
#
# a vector of file name strings representing absolute paths to TDL files
#
choose_input_tdl_files <- function()
{
    if (!interactive() | .Platform$OS.type != "windows") {
        stop(
            paste(
                "The `choose_input_tdl_files` function is only available in",
                "interactive R sessions running in MS Windows"
            )
        )
    }

    choose.files(
        default = "",
        caption = "Select TDL input files",
        multi = TRUE,
        filters = matrix(
            c(
                "TDL files (*.dat)", "All files (*.*)",
                "*.dat", "*.*"
            ),
            ncol = 2
        ),
        index = 1
    )
}
